//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cierre_ProgramaVta_Detalle
    {
        public int id_cierreProVta { get; set; }
        public int id_ClasCorp { get; set; }
        public Nullable<int> Cuota_ProVta { get; set; }
        public Nullable<int> UnidadesPedidas { get; set; }
        public string NumPedido_comp { get; set; }
        public string userModif { get; set; }
    
        public virtual Cierre_ProVta Cierre_ProVta { get; set; }
    }
}
