//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estatus_ProVta
    {
        public Estatus_ProVta()
        {
            this.Cierre_ProVta = new HashSet<Cierre_ProVta>();
        }
    
        public int idStatus { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fhc_modif { get; set; }
        public string usermodif { get; set; }
    
        public virtual ICollection<Cierre_ProVta> Cierre_ProVta { get; set; }
    }
}
