//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPEntities : DbContext
    {
        public SPEntities()
            : base("name=SPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cierre_ProgramaVta_Detalle> Cierre_ProgramaVta_Detalle { get; set; }
        public DbSet<Cierre_ProVta> Cierre_ProVta { get; set; }
        public DbSet<Estatus_ProVta> Estatus_ProVta { get; set; }
        public DbSet<Periodo> Periodos { get; set; }
        public DbSet<PlazoComercial> PlazoComercials { get; set; }
        public DbSet<ProgramaVta> ProgramaVtas { get; set; }
        public DbSet<ProgramaVtaDetalleCuota> ProgramaVtaDetalleCuotas { get; set; }
        public DbSet<ProgramaVtaDetalleSPA> ProgramaVtaDetalleSPAs { get; set; }
        public DbSet<Tipo_Periodos> Tipo_Periodos { get; set; }
        public DbSet<vwProgramaVta> vwProgramaVtas { get; set; }
    }
}
