//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlazoComercial
    {
        public PlazoComercial()
        {
            this.ProgramaVtaDetalleCuotas = new HashSet<ProgramaVtaDetalleCuota>();
            this.ProgramaVtaDetalleSPAs = new HashSet<ProgramaVtaDetalleSPA>();
        }
    
        public int id_PlazoComercial { get; set; }
        public string descripcion { get; set; }
        public string estatus { get; set; }
        public Nullable<double> Porcentaje_Sustitucion_USD { get; set; }
        public Nullable<double> Porcentaje_Sustitucion_NMX { get; set; }
    
        public virtual ICollection<ProgramaVtaDetalleCuota> ProgramaVtaDetalleCuotas { get; set; }
        public virtual ICollection<ProgramaVtaDetalleSPA> ProgramaVtaDetalleSPAs { get; set; }
    }
}
