//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaVtaDetalleCuota
    {
        public int idProgramaVta { get; set; }
        public int id_Gfx { get; set; }
        public Nullable<int> id_clascorp { get; set; }
        public int id_TipoPeriodo { get; set; }
        public int id_Periodo { get; set; }
        public string Tipo_cuota { get; set; }
        public Nullable<int> cuota { get; set; }
        public int id_PlazoComercial { get; set; }
    
        public virtual Periodo Periodo { get; set; }
        public virtual PlazoComercial PlazoComercial { get; set; }
        public virtual ProgramaVta ProgramaVta { get; set; }
    }
}
