//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCDMC_Distribuidor
    {
        public int cd_empresa { get; set; }
        public int cd_marca { get; set; }
        public int cd_distribuidor { get; set; }
        public string nb_razonsocial { get; set; }
        public string nb_alias { get; set; }
        public string tx_rfc { get; set; }
    }
}
