//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generador
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProVtaDealer
    {
        public int idProgramaVta { get; set; }
        public string nombre { get; set; }
        public int id_Gfx { get; set; }
    }
}
